### ISSUE TITLE
Too many versions of game.py

### ISSUE THREAD

**Issue by antoniosehk** [antoniosehk/space-app-2019#13]
We have one game.py
        and one game-demo.py

Better naming would be game-level-1.py and game-level-2.py

**Comment by hector12free** [comment]
I added the game-demo.py because we wanted that hackey version to do the demo. We can actually remove it now, and we will/are handling all levels in the same script: game.py

What do you think?

**Comment by hector12free** [comment]
@wxy517 You can assign this issue to yourself if you want to work on another one. 😃

**Comment by wxy517** [comment]
close this issue as it's fixed in #24
